Feature comments
Charchit507/demo-app pull request #4
Opened 2022-08-22 09:26 UTC by Charchit507

2022-08-22 13:59 UTC, neeteshgupta95 requested changes

2022-08-22 13:59 UTC, neeteshgupta95 commented on app/views/comments/_comment.html.erb
> +  <%= comment.user.first_name %>&nbsp<%= comment.user.last_name %>
create one method in the User model with `full_name` and use same method here

2022-08-23 06:07 UTC, neeteshgupta95 requested changes

2022-08-23 06:07 UTC, neeteshgupta95 commented on app/models/user.rb
> +    self.first_name << " " << self.last_name
1. remove self 
2 use interpolation

2022-08-23 06:07 UTC, neeteshgupta95 commented on app/models/user.rb
> +  def fullname
rename it to `full_name`

2022-08-23 06:08 UTC, Charchit507 commented on app/models/user.rb
> +    self.first_name << " " << self.last_name
okay

2022-08-23 06:08 UTC, Charchit507 commented on app/models/user.rb
> +  def fullname
okay

2022-08-23 06:45 UTC, neeteshgupta95 approved these changes

2022-08-23 06:45 UTC, merged